### ISSUE TITLE
Clear up completed milestones

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngi_pipeline#148]
![your mom](http://www.thefunnypage.com/images/yo-mama-so-fat.jpg)

**Comment by mariogiov** [comment]
I talked to my Mom last weekend so I think I'll close this. Thanks mom!

**Comment by ewels** [comment]
![yo mama](http://www.troll.me/images/thumbs-up-jesus-says/hey-yo-mama.jpg)
