### ISSUE TITLE
Cron job to update Charon and send relevant emails

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#171]
I'm gonna set up a cron job to run the script that updates Charon with running/finished/failed job statuses and also sends notification emails to operators.

**Comment by mariogiov** [comment]
Alright I think this is working now and should update/send emails each hour. The crontab looks like:

```bash
SHELL=/bin/bash
0 * * * * source $HOME/.bashrc && update_charon_with_local_jobs_status.py -e piper
```

**Comment by guillermo-carrasco** [comment]
looks good :-D :+1:
