### ISSUE TITLE
Don't copy files back from scratch if piper fails

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#179]
We need to modify the sbatch script so that it doesn't copy files back from scratch to permanent storage if the Piper run failed (at the moment it copies everything regardless).

**Comment by vezzi** [comment]
@mariogiov in many cases this might be a good behaviour... it might allow us to know where things failed...

**Comment by mariogiov** [comment]
That is a good point. Well hm. Let's sit down and decide how we want to do this.

**Comment by mariogiov** [comment]
I think it's better to check the logs to see what failed than to transfer back a bunch of files we'll have to delete again later. Is that alright? @vezzi

**Comment by vezzi** [comment]
@mariogiov makes sense,
