### ISSUE TITLE
Add group sticky bit to directories created by the pipeline

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#184]
I'd like all these directories to inherit group ownership of `a2014205` whereas at the moment they're user/group owned `funk_002`.

**Comment by mariogiov** [comment]
This should be as simple as changing the parameters to `safe_makedir()`

**Comment by mariogiov** [comment]
Huh. `ANALYSIS` and `DATA` both already have the group sticky bit set so this should already be happening. That's odd.

**Comment by guillermo-carrasco** [comment]
group sticky bits will only be set for files and directories *created* inside the directory that has the sticky bit. If you *move* a file there, the sticky bit will not work. Is that the case?

**Comment by mariogiov** [comment]
Mm, that's a good point but we're creating all these files and dirs so I don't think that's it in this case.

**Comment by guillermo-carrasco** [comment]
then... google #FTW :-P sorry

**Comment by mariogiov** [comment]
It turns out I was manually setting the directory permissions incorrectly in my call to `safe_makedir` (I was using `0770` but should have used `0o2770`).
