### ISSUE TITLE
Xten run failed, wrong name of sample folders

### ISSUE THREAD

**Issue by Galithil** [NationalGenomicsInfrastructure/ngi_pipeline#198]
Permissions error when trying to update Charon status for "project/sample J.Lundeberg_14_24/P1775_118": Piper qc directories under "/proj/a2014205/nobackup/NGI/analysis_ready/ANALYSIS/P1775/02_preliminary_alignment_qc/P1775_118.AK00AAA3XX.P1775_118*/" are missing or in an unexpected format when updating stats to Charon.

The folder is named : 
P1775-118.AK00AAA3XX.P1775-118.1.qc
note the hyphen instead of the underscore. 
Find out why and fix.

**Comment by Galithil** [comment]
The fastq names are P1775-118_S1_L001_R1_001.fastq.gz  P1775-118_S1_L001_R2_001.fastq.gz
Hyphen here too. Is that supposed to be changed by the pipeline at some point ?

**Comment by mariogiov** [comment]
I thought I fixed this here actually:

https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/pull/195/files#diff-115ce865bfa2492f16ba17f8f85488fdR370

but perhaps I didn't?

**Comment by mariogiov** [comment]
Aha or no that was just a similar problem. Maybe it's better to make that change somewhere higher in the code.

**Comment by Galithil** [comment]
so you are _not_ dead then ? Pelin is looking for you btw.

You mean that this is normal and that the pipeline should handle it then. looking into it then.

**Comment by Galithil** [comment]
fixed by #199
