### ISSUE TITLE
Fix so we can process multiple flowcells simultaneously

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#200]
This should be an easy fix: just pluralize the method name here:

https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/blob/devel/scripts/ngi_pipeline_start.py#L65

**Comment by guillermo-carrasco** [comment]
If it takes the same parameters, yep

**Comment by mariogiov** [comment]
Fixed!
