### ISSUE TITLE
Is the pipeline copying Pipers hidden files?

### ISSUE THREAD

**Issue by johandahlberg** [NationalGenomicsInfrastructure/ngi_pipeline#203]
I was looking at a project that had failed just now, and locking at the logs it looks like the pipeline copies back the alignments from previous runs (if it can find them), but that it doesn't copy the accompanying hidden files which Queue uses to track which jobs have completed or not. So if those files are not also copied to scratch it will rerun everything, even if it had finished before.

**Comment by mariogiov** [comment]
Well that is an annoying oversight. Alright lemme see what I can rustle up.

**Comment by mariogiov** [comment]
@johandahlberg can you direct me to a Piper output directory that has these files or tell me the format? I gotta fix up the `glob`.

**Comment by johandahlberg** [comment]
For every file that piper generates there is a accompanying hidden file, so you should be able to see it in any output folder if you do a `ls -la`.

**Comment by mariogiov** [comment]
Right but those files are not at this point copied back from scratch to permanent storage so I can't see 'em

**Comment by johandahlberg** [comment]
Why don't you just copy back the folder containing the files that you are interested in when coming back from the node? Something like `rsync <args> /<output_folder>/01_raw_alignements/* <target>`?

**Comment by mariogiov** [comment]
Ah, my mistake. The rsync actually does copy the hidden back from scratch to permanent as it stands, so I just need to modify it when it's doing the reverse (more selective sample-based copy).

**Comment by mariogiov** [comment]
Well now it copies them back from scratch-->permanent and we never copy them the other way around so I'm closing this.
