### ISSUE TITLE
Fix sample sheet parser to work with new sample sheets

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#204]
They're gzipped sometimes as well

**Comment by guillermo-carrasco** [comment]
the saplesheets?

**Comment by mariogiov** [comment]
Yeah the format changed. Also the compression.

**Comment by mariogiov** [comment]
This broke a bunch of Uppsala runs so this is the new Top Priority Bug.

**Comment by mariogiov** [comment]
Fixed
