### ISSUE TITLE
Delete files when re-running instead of rotating to previous_analyses

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#214]
Francesco suggested we just delete them which I think is fine. Pär agrees, so let's just implement it.

**Comment by mariogiov** [comment]
Implemented

**Comment by guillermo-carrasco** [comment]
you know that you can close issues by referencing them on commit messages right? Just FYI :-)

**Comment by mariogiov** [comment]
Right! I always forget. I will remember in the future
