### ISSUE TITLE
NGI Node information in XML setup file

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngi_pipeline#243]
At the moment it's almost impossible to find out which node sequenced the data. We need this information for running the reports.

The setup XML files currently have the following (hard coded) string:

```xml
<sequenceingcenter>NGI</sequenceingcenter>
```

Two things:

1. @johandahlberg: `sequenceingcenter` is spelt wrong, it should be `sequencingcenter` :neckbeard: 
2. @mariogiov: We have this info, right? So can we add it to the XML file? Sounds easy! :grin: 

Tack!

**Comment by johandahlberg** [comment]
While I reject the idea of there being a correct spelling, I'll add it as an issue in the Piper repo. :wink:

**Comment by ewels** [comment]
![spelling](http://memeshare.net/memes/15/14038.png)

**Comment by mariogiov** [comment]
I reject the idea that anyone should do anything in XML but I'll do my darndest anyway as well.

**Comment by ewels** [comment]
I had thought that myself. JSON >> XML, no?

**Comment by mariogiov** [comment]
Okay so I'm getting this from Charon -- if for some reason it's not available, I'm setting it to blank (`""`). If you'd prefer another value, holla atchya boy

**Comment by ewels** [comment]
Nice - I've implemented this [at my end](https://github.com/ewels/ngi_reports/blob/master/scripts/ngi_reports#L45-L49) too..

Thanks!
