### ISSUE TITLE
When restarting a Piper analysis job, we should remove the old coverage value

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#252]

**Comment by Galithil** [comment]
the coverage should be updated on seqrun update, and will discard failed seqruns, so....

**Comment by mariogiov** [comment]
This is true but if we restart the seqruns, they can have status `UNDER_ANALYSIS` or `FAILED` and still have the old coverage value, which is kind of icky

**Comment by mariogiov** [comment]
Fixed https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/pull/258
