### ISSUE TITLE
Decide how to track genotyping in the piper_ngi code

### ISSUE THREAD

**Issue by mariogiov** [NationalGenomicsInfrastructure/ngi_pipeline#274]
I implemented the `genotype()` function separately from the standard `analyze()` function because there's no way to track this in Charon at the moment, but I think it would make sense to track it there -- we need to add a field for `genotype_status` or something. Otherwise we'll have to maintain two separate almost-identical functions which is annoying and not DRY.
Once we have such a field, it's set up relatively well (using the `level` flag) so that it should be simple to take steps differently within the `analyze()` code instead of having two separate functions.
See [here](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/blob/devel/ngi_pipeline/engines/piper_ngi/launchers.py#L155), [here](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/blob/devel/ngi_pipeline/engines/piper_ngi/launchers.py#L185), [here](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/blob/devel/ngi_pipeline/engines/piper_ngi/local_process_tracking.py#L83), [here](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/blob/devel/ngi_pipeline/engines/piper_ngi/local_process_tracking.py#L369), etc.

**Comment by mariogiov** [comment]
@Galithil @vezzi

**Comment by mariogiov** [comment]
I can probably pretty easily fix this once we implement the field in Charon. I meant to bring this up before I left but then I barely left the country in time with all my things.
I would suggest a field `genotype_status` on the sample and also on the sequn level.

**Comment by vezzi** [comment]
Hej @mariogiov thanks for this tip.
On seqrun level might be difficult to track it in charon.... makes perfect sense at sample level.

The problem right now is more operational: we receive genotyping weeks after the sequencing and anlysis are done. Moreover we receive it in batches (several projects). For me it makes more sense to leave the gneotyping checking a bit manual, in the sense that the operator runs it once the genotype info is received. Once the way in which we genotype will be defined and stable then we can stabilise the pipeline. 

Anyway I like to integrate the genotype in Charon

**Comment by mariogiov** [comment]
Right, at the moment the genotype analysis is only run manually via the `ngi_pipeline_start.py` script -- but would tracking this in Charon cause any problems? It would still be manual but you'd be able to get a quick overview of which samples/seqruns have been verified and which haven't. Also tracking on the seqrun or libprep level would be good because this is where sample mixups would happen, which I think is our primary concern and the reason for running the genotypes. Right?

**Comment by vezzi** [comment]
yep right. My concern was in not trying to automate too much, genotyping checking will remain manual for a certain time. But I totlly agree on the need of tracking. THis will allow to add this info to the reports
