### ISSUE TITLE
flowcells in a2015179 not found

### ISSUE THREAD

**Issue by b97pla** [NationalGenomicsInfrastructure/ngi_pipeline#301]
- when launching analysis using just the fcid and not the full path, the pipeline will search in the path specified by `environment.flowcell_inbox` in the config. currently, this path points to a2014205
- a quick fix is to list multiple paths under `flowcell_inbox` and search all of them
- an option that works out-of-the-box is to specify the full path when triggering analysis
- it should, however, be investigated which parts of the pipeline are dependent on having a path that includes the project_id and how the fact that we have started using two projects are affecting this

**Comment by mariogiov** [comment]
Was this fixed in [#302](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/pull/302)?

**Comment by mariogiov** [comment]
+1 to @b97pla for suggesting multiple possible solutions. I love science people.

**Comment by b97pla** [comment]
I believe this is fixed for now by @Galithil
